# Generated by Django 4.2.6 on 2024-01-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_creaation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'private')], default='Pablic', max_length=50)),
                ('event_category', models.ManyToManyField(blank=True, null=True, to='EventCategory.event_category')),
            ],
        ),
    ]
