# Generated by Django 4.2.6 on 2024-01-16 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventCategory', '0001_initial'),
        ('Event_creation', '0002_alter_event_creaation_model_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_creaation_model',
            name='event_category',
        ),
        migrations.AddField(
            model_name='event_creaation_model',
            name='event_category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='EventCategory.event_category'),
        ),
    ]
