# Generated by Django 4.2.6 on 2024-01-16 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventCategory', '0001_initial'),
        ('Event_creation', '0003_remove_event_creaation_model_event_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_creation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'private')], default='Pablic', max_length=50)),
                ('event_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventCategory.event_category')),
            ],
        ),
        migrations.DeleteModel(
            name='Event_creaation_model',
        ),
    ]
