# Generated by Django 4.2.6 on 2024-01-17 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event_creation', '0004_event_creation_model_delete_event_creaation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_creation_model',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event_creation_model',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
