# Generated by Django 4.2.6 on 2024-01-17 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event_creation', '0005_event_creation_model_count_event_creation_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_creation_model',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
