# Generated by Django 4.2.6 on 2024-01-17 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event_creation', '0008_remove_event_creation_model_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('evnet_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_creation.event_creation_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
