# Generated by Django 4.2.6 on 2024-01-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_creation', '0009_confirm_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm_event',
            name='evnet_creation',
        ),
        migrations.AddField(
            model_name='confirm_event',
            name='evnet_creation',
            field=models.ManyToManyField(to='Event_creation.event_creation_model'),
        ),
    ]
