# Generated by Django 4.2.6 on 2024-01-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_creation', '0010_remove_confirm_event_evnet_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_event',
            name='evnet_creation',
            field=models.ManyToManyField(related_name='save_events', to='Event_creation.event_creation_model'),
        ),
    ]
