# Generated by Django 4.2.6 on 2024-01-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_creation', '0011_alter_confirm_event_evnet_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm_event',
            old_name='evnet_creation',
            new_name='save_events',
        ),
    ]
