# Generated by Django 4.2.6 on 2024-01-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_creation', '0012_rename_evnet_creation_confirm_event_save_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_creation_model',
            old_name='confirmed_users',
            new_name='user',
        ),
    ]
