# Generated by Django 4.2.6 on 2024-01-18 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event_creation', '0014_remove_event_creation_model_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_creation_model',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
