# Generated by Django 4.2.6 on 2024-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_creation', '0016_confirm_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_event',
            name='event_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20, null=True),
        ),
    ]
